import type { DashboardData } from '@/lib/eu/types'

const today = new Date()
const addDays = (d: Date, n: number) => new Date(d.getTime() + n * 86400000).toISOString().split('T')[0]

export const MOCK_DATA: DashboardData = {
  organisation: {
    id: 'org-1',
    owner_user_id: 'user-1',
    nom: 'Lumia Technologies',
    plan_abonnement: 'scale',
    created_at: '2023-06-01T10:00:00Z',
    updated_at: '2025-01-15T10:00:00Z',
  },
  entites: [
    {
      id: 'ent-fr',
      organisation_id: 'org-1',
      nom_legal: 'Lumia Technologies SAS',
      forme_juridique: 'SAS',
      pays: 'FR',
      numero_registre: '893 456 789',
      date_immatriculation: '2023-06-01',
      capital_social: 10000,
      devise: 'EUR',
      siege_social: { rue: '15 rue du Faubourg Saint-Antoine', cp: '75011', ville: 'Paris', pays: 'France' },
      statut: 'active',
      created_at: '2023-06-01T10:00:00Z',
      updated_at: '2025-01-15T10:00:00Z',
      obligations: [
        {
          id: 'obl-fr-1',
          entite_id: 'ent-fr',
          titre: 'Assemblée Générale Annuelle 2025',
          type: 'ag_annuelle',
          echeance: addDays(today, 3),
          statut: 'a_faire',
          priorite: 'urgente',
          description: 'AG annuelle obligatoire — approbation des comptes 2024',
          created_at: '2025-01-01T10:00:00Z',
        },
        {
          id: 'obl-fr-2',
          entite_id: 'ent-fr',
          titre: 'Dépôt des comptes 2024 au greffe',
          type: 'depot_comptes',
          echeance: addDays(today, 10),
          statut: 'a_faire',
          priorite: 'haute',
          description: 'Dépôt obligatoire dans les 6 mois suivant la clôture — INPI',
          created_at: '2025-01-01T10:00:00Z',
        },
        {
          id: 'obl-fr-3',
          entite_id: 'ent-fr',
          titre: 'Déclaration TVA T1 2026',
          type: 'declaration_fiscale',
          echeance: addDays(today, 28),
          statut: 'a_faire',
          priorite: 'normale',
          created_at: '2025-01-01T10:00:00Z',
        },
      ],
      representants: [
        {
          id: 'rep-fr-1',
          entite_id: 'ent-fr',
          nom_complet: 'Sarah Chen',
          email: 'sarah@lumia.io',
          role: 'Présidente',
          date_debut: '2023-06-01',
          created_at: '2023-06-01T10:00:00Z',
        },
        {
          id: 'rep-fr-2',
          entite_id: 'ent-fr',
          nom_complet: 'Marc Dupont',
          email: 'marc@lumia.io',
          role: 'Directeur Général',
          date_debut: '2023-09-01',
          created_at: '2023-09-01T10:00:00Z',
        },
      ],
      documents: [
        {
          id: 'doc-fr-1', entite_id: 'ent-fr', nom: 'Extrait Kbis — Janvier 2025', type: 'extrait_kbis',
          langue: 'fr', date_emission: '2025-01-15', est_certificat_eu: false,
          created_at: '2025-01-15T10:00:00Z',
        },
        {
          id: 'doc-fr-2', entite_id: 'ent-fr', nom: 'Statuts constitutifs', type: 'statuts',
          langue: 'fr', date_emission: '2023-06-01', est_certificat_eu: false,
          created_at: '2023-06-01T10:00:00Z',
        },
        {
          id: 'doc-fr-3', entite_id: 'ent-fr', nom: 'PV AG 2024', type: 'pv_ag',
          langue: 'fr', date_emission: '2024-06-20', est_certificat_eu: false,
          created_at: '2024-06-20T10:00:00Z',
        },
        {
          id: 'doc-fr-4', entite_id: 'ent-fr', nom: 'EU Company Certificate — 2025', type: 'eu_certificate',
          langue: 'fr', date_emission: '2025-03-01', date_expiration: '2026-03-01', est_certificat_eu: true,
          created_at: '2025-03-01T10:00:00Z',
        },
      ],
      associes: [
        { id: 'ass-1', entite_id: 'ent-fr', nom: 'Sarah Chen', type: 'fondateur', nb_actions: 4500, type_actions: 'ordinaires', date_entree: '2023-06-01', created_at: '2023-06-01T10:00:00Z' },
        { id: 'ass-2', entite_id: 'ent-fr', nom: 'Marc Dupont', type: 'fondateur', nb_actions: 3000, type_actions: 'ordinaires', date_entree: '2023-06-01', created_at: '2023-06-01T10:00:00Z' },
        { id: 'ass-3', entite_id: 'ent-fr', nom: 'TechFund I', email: 'invest@techfund.vc', type: 'investisseur', nb_actions: 1500, type_actions: 'préférence A', date_entree: '2024-03-01', created_at: '2024-03-01T10:00:00Z' },
        { id: 'ass-4', entite_id: 'ent-fr', nom: 'ESOP Pool', type: 'esop_pool', nb_actions: 1000, type_actions: 'ordinaires', date_entree: '2023-06-01', created_at: '2023-06-01T10:00:00Z' },
      ],
    },
    {
      id: 'ent-de',
      organisation_id: 'org-1',
      entite_parente_id: 'ent-fr',
      nom_legal: 'Lumia Technologies GmbH',
      forme_juridique: 'GmbH',
      pays: 'DE',
      numero_registre: 'HRB 234567 B',
      date_immatriculation: '2024-02-15',
      capital_social: 25000,
      devise: 'EUR',
      siege_social: { rue: 'Torstraße 61', cp: '10119', ville: 'Berlin', pays: 'Deutschland' },
      statut: 'active',
      created_at: '2024-02-15T10:00:00Z',
      updated_at: '2025-05-10T10:00:00Z',
      obligations: [
        {
          id: 'obl-de-1',
          entite_id: 'ent-de',
          titre: 'Mise à jour Handelsregister — Changement adresse',
          type: 'mise_a_jour_registre',
          echeance: addDays(today, 7),
          statut: 'a_faire',
          priorite: 'urgente',
          description: 'Cadre européen — délai max 15 jours ouvrables après changement',
          created_at: '2025-05-10T10:00:00Z',
        },
        {
          id: 'obl-de-2',
          entite_id: 'ent-de',
          titre: 'Gesellschafterversammlung 2025',
          type: 'ag_annuelle',
          echeance: addDays(today, 32),
          statut: 'a_faire',
          priorite: 'normale',
          created_at: '2025-01-01T10:00:00Z',
        },
      ],
      representants: [
        {
          id: 'rep-de-1',
          entite_id: 'ent-de',
          nom_complet: 'Sarah Chen',
          email: 'sarah@lumia.io',
          role: 'Geschäftsführerin',
          date_debut: '2024-02-15',
          created_at: '2024-02-15T10:00:00Z',
        },
        {
          id: 'rep-de-2',
          entite_id: 'ent-de',
          nom_complet: 'Thomas Wagner',
          email: 'thomas@lumia.de',
          role: 'Prokurist',
          date_debut: '2024-04-01',
          created_at: '2024-04-01T10:00:00Z',
        },
      ],
      documents: [
        {
          id: 'doc-de-1', entite_id: 'ent-de', nom: 'Handelsregisterauszug Mars 2025', type: 'extrait_kbis',
          langue: 'de', date_emission: '2025-03-01', est_certificat_eu: false,
          created_at: '2025-03-01T10:00:00Z',
        },
        {
          id: 'doc-de-2', entite_id: 'ent-de', nom: 'Gesellschaftsvertrag', type: 'statuts',
          langue: 'de', date_emission: '2024-02-15', est_certificat_eu: false,
          created_at: '2024-02-15T10:00:00Z',
        },
      ],
      associes: [
        { id: 'ass-de-1', entite_id: 'ent-de', nom: 'Lumia Technologies SAS', type: 'fondateur', nb_actions: 25000, type_actions: 'parts sociales', date_entree: '2024-02-15', created_at: '2024-02-15T10:00:00Z' },
      ],
    },
    {
      id: 'ent-nl',
      organisation_id: 'org-1',
      entite_parente_id: 'ent-fr',
      nom_legal: 'Lumia Technologies BV',
      forme_juridique: 'BV',
      pays: 'NL',
      numero_registre: 'KvK 92345678',
      date_immatriculation: '2025-04-10',
      capital_social: 100,
      devise: 'EUR',
      siege_social: { rue: 'Keizersgracht 462', cp: '1017 EG', ville: 'Amsterdam', pays: 'Nederland' },
      statut: 'en_creation',
      created_at: '2025-04-10T10:00:00Z',
      updated_at: '2025-05-01T10:00:00Z',
      obligations: [
        {
          id: 'obl-nl-1',
          entite_id: 'ent-nl',
          titre: 'Enregistrement KvK — finalisation',
          type: 'mise_a_jour_registre',
          echeance: addDays(today, 15),
          statut: 'a_faire',
          priorite: 'haute',
          description: 'Dépôt des statuts définitifs et activation du numéro KvK',
          created_at: '2025-04-10T10:00:00Z',
        },
        {
          id: 'obl-nl-2',
          entite_id: 'ent-nl',
          titre: 'Ouverture compte bancaire ING',
          type: 'autre',
          echeance: addDays(today, 20),
          statut: 'a_faire',
          priorite: 'haute',
          created_at: '2025-04-10T10:00:00Z',
        },
      ],
      representants: [
        {
          id: 'rep-nl-1',
          entite_id: 'ent-nl',
          nom_complet: 'Pieter van Bergen',
          email: 'pieter@lumia.nl',
          role: 'Directeur',
          date_debut: '2025-04-10',
          created_at: '2025-04-10T10:00:00Z',
        },
      ],
      documents: [
        {
          id: 'doc-nl-1', entite_id: 'ent-nl', nom: 'Acte de constitution BV', type: 'statuts',
          langue: 'nl', date_emission: '2025-04-10', est_certificat_eu: false,
          created_at: '2025-04-10T10:00:00Z',
        },
      ],
      associes: [
        { id: 'ass-nl-1', entite_id: 'ent-nl', nom: 'Lumia Technologies SAS', type: 'fondateur', nb_actions: 100, type_actions: 'ordinaires', date_entree: '2025-04-10', created_at: '2025-04-10T10:00:00Z' },
      ],
    },
  ],
  activity: [
    { id: 'act-1', organisation_id: 'org-1', entite_id: 'ent-de', user_nom: 'Sarah Chen', action: 'Mise à jour adresse siège social — Torstraße 61, Berlin', details: {}, created_at: new Date(today.getTime() - 2 * 3600000).toISOString() },
    { id: 'act-2', organisation_id: 'org-1', entite_id: 'ent-fr', user_nom: 'Marc Dupont', action: 'Document uploadé : Extrait Kbis — Janvier 2025', details: {}, created_at: new Date(today.getTime() - 24 * 3600000).toISOString() },
    { id: 'act-3', organisation_id: 'org-1', user_nom: 'Système', action: 'Rappel envoyé : AG Annuelle SAS dans 3 jours', details: {}, created_at: new Date(today.getTime() - 2 * 24 * 3600000).toISOString() },
    { id: 'act-4', organisation_id: 'org-1', entite_id: 'ent-nl', user_nom: 'Sarah Chen', action: 'Création filiale Lumia Technologies BV — Pays-Bas', details: {}, created_at: new Date(today.getTime() - 7 * 24 * 3600000).toISOString() },
    { id: 'act-5', organisation_id: 'org-1', entite_id: 'ent-fr', user_nom: 'Marc Dupont', action: 'EU Company Certificate généré (FR)', details: {}, created_at: new Date(today.getTime() - 14 * 24 * 3600000).toISOString() },
    { id: 'act-6', organisation_id: 'org-1', entite_id: 'ent-de', user_nom: 'Thomas Wagner', action: 'Représentant ajouté : Thomas Wagner — Prokurist', details: {}, created_at: new Date(today.getTime() - 20 * 24 * 3600000).toISOString() },
  ],
  membres: [
    { id: 'mb-1', organisation_id: 'org-1', user_id: 'user-1', email: 'laurent.minguez@gmail.com', role: 'owner', invited_at: '2023-06-01T10:00:00Z', accepted_at: '2023-06-01T10:00:00Z' },
  ],
}
